// source: sensoris/protobuf/categories/driving_behavior.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var sensoris_protobuf_types_base_pb = require('../../../sensoris/protobuf/types/base_pb.js');
goog.object.extend(proto, sensoris_protobuf_types_base_pb);
goog.exportSymbol('proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.Type', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.Type', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.displayName = 'proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.displayName = 'proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.displayName = 'proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.repeatedFields_, null);
};
goog.inherits(proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.displayName = 'proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    envelope: (f = msg.getEnvelope()) && sensoris_protobuf_types_base_pb.EventEnvelope.toObject(includeInstance, f),
    statusAndConfidence: (f = msg.getStatusAndConfidence()) && proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.toObject(includeInstance, f),
    directionAndConfidence: (f = msg.getDirectionAndConfidence()) && proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.toObject(includeInstance, f),
    durationAndAccuracy: (f = msg.getDurationAndAccuracy()) && sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus;
  return proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new sensoris_protobuf_types_base_pb.EventEnvelope;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.EventEnvelope.deserializeBinaryFromReader);
      msg.setEnvelope(value);
      break;
    case 2:
      var value = new proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence;
      reader.readMessage(value,proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.deserializeBinaryFromReader);
      msg.setStatusAndConfidence(value);
      break;
    case 3:
      var value = new proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence;
      reader.readMessage(value,proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.deserializeBinaryFromReader);
      msg.setDirectionAndConfidence(value);
      break;
    case 4:
      var value = new sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy.deserializeBinaryFromReader);
      msg.setDurationAndAccuracy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvelope();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      sensoris_protobuf_types_base_pb.EventEnvelope.serializeBinaryToWriter
    );
  }
  f = message.getStatusAndConfidence();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.serializeBinaryToWriter
    );
  }
  f = message.getDirectionAndConfidence();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.serializeBinaryToWriter
    );
  }
  f = message.getDurationAndAccuracy();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    confidence: (f = msg.getConfidence()) && sensoris_protobuf_types_base_pb.Confidence.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence;
  return proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new sensoris_protobuf_types_base_pb.Confidence;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.Confidence.deserializeBinaryFromReader);
      msg.setConfidence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getConfidence();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      sensoris_protobuf_types_base_pb.Confidence.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.Type = {
  UNKNOWN_TYPE: 0,
  PARK_IN: 1,
  PARK_OUT: 2
};

/**
 * optional Type type = 1;
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.Type}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.prototype.getType = function() {
  return /** @type {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.Type} value
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence} returns this
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional sensoris.protobuf.types.base.Confidence confidence = 2;
 * @return {?proto.sensoris.protobuf.types.base.Confidence}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.prototype.getConfidence = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.Confidence} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.Confidence, 2));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.Confidence|undefined} value
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence} returns this
*/
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.prototype.setConfidence = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence} returns this
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.prototype.clearConfidence = function() {
  return this.setConfidence(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.prototype.hasConfidence = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    confidence: (f = msg.getConfidence()) && sensoris_protobuf_types_base_pb.Confidence.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence;
  return proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new sensoris_protobuf_types_base_pb.Confidence;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.Confidence.deserializeBinaryFromReader);
      msg.setConfidence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getConfidence();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      sensoris_protobuf_types_base_pb.Confidence.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.Type = {
  UNKNOWN_TYPE: 0,
  LONGITUDINAL: 1,
  LATERAL: 2,
  DIAGONAL: 3
};

/**
 * optional Type type = 1;
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.Type}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.prototype.getType = function() {
  return /** @type {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.Type} value
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence} returns this
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional sensoris.protobuf.types.base.Confidence confidence = 2;
 * @return {?proto.sensoris.protobuf.types.base.Confidence}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.prototype.getConfidence = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.Confidence} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.Confidence, 2));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.Confidence|undefined} value
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence} returns this
*/
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.prototype.setConfidence = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence} returns this
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.prototype.clearConfidence = function() {
  return this.setConfidence(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.prototype.hasConfidence = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional sensoris.protobuf.types.base.EventEnvelope envelope = 1;
 * @return {?proto.sensoris.protobuf.types.base.EventEnvelope}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.getEnvelope = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.EventEnvelope} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.EventEnvelope, 1));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.EventEnvelope|undefined} value
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus} returns this
*/
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.setEnvelope = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus} returns this
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.clearEnvelope = function() {
  return this.setEnvelope(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.hasEnvelope = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional StatusAndConfidence status_and_confidence = 2;
 * @return {?proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.getStatusAndConfidence = function() {
  return /** @type{?proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence} */ (
    jspb.Message.getWrapperField(this, proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence, 2));
};


/**
 * @param {?proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence|undefined} value
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus} returns this
*/
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.setStatusAndConfidence = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus} returns this
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.clearStatusAndConfidence = function() {
  return this.setStatusAndConfidence(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.hasStatusAndConfidence = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional DirectionAndConfidence direction_and_confidence = 3;
 * @return {?proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.getDirectionAndConfidence = function() {
  return /** @type{?proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence} */ (
    jspb.Message.getWrapperField(this, proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence, 3));
};


/**
 * @param {?proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence|undefined} value
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus} returns this
*/
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.setDirectionAndConfidence = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus} returns this
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.clearDirectionAndConfidence = function() {
  return this.setDirectionAndConfidence(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.hasDirectionAndConfidence = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional sensoris.protobuf.types.base.Int64ValueAndAccuracy duration_and_accuracy = 4;
 * @return {?proto.sensoris.protobuf.types.base.Int64ValueAndAccuracy}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.getDurationAndAccuracy = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.Int64ValueAndAccuracy} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy, 4));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.Int64ValueAndAccuracy|undefined} value
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus} returns this
*/
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.setDurationAndAccuracy = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus} returns this
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.clearDurationAndAccuracy = function() {
  return this.setDurationAndAccuracy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.prototype.hasDurationAndAccuracy = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.toObject = function(includeInstance, msg) {
  var f, obj = {
    envelope: (f = msg.getEnvelope()) && sensoris_protobuf_types_base_pb.CategoryEnvelope.toObject(includeInstance, f),
    parkingStatusList: jspb.Message.toObjectList(msg.getParkingStatusList(),
    proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory}
 */
proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory;
  return proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory}
 */
proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new sensoris_protobuf_types_base_pb.CategoryEnvelope;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.CategoryEnvelope.deserializeBinaryFromReader);
      msg.setEnvelope(value);
      break;
    case 2:
      var value = new proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus;
      reader.readMessage(value,proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.deserializeBinaryFromReader);
      msg.addParkingStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvelope();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      sensoris_protobuf_types_base_pb.CategoryEnvelope.serializeBinaryToWriter
    );
  }
  f = message.getParkingStatusList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.serializeBinaryToWriter
    );
  }
};


/**
 * optional sensoris.protobuf.types.base.CategoryEnvelope envelope = 1;
 * @return {?proto.sensoris.protobuf.types.base.CategoryEnvelope}
 */
proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.prototype.getEnvelope = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.CategoryEnvelope} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.CategoryEnvelope, 1));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.CategoryEnvelope|undefined} value
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory} returns this
*/
proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.prototype.setEnvelope = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory} returns this
 */
proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.prototype.clearEnvelope = function() {
  return this.setEnvelope(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.prototype.hasEnvelope = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated ParkingStatus parking_status = 2;
 * @return {!Array<!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus>}
 */
proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.prototype.getParkingStatusList = function() {
  return /** @type{!Array<!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus, 2));
};


/**
 * @param {!Array<!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus>} value
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory} returns this
*/
proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.prototype.setParkingStatusList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus}
 */
proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.prototype.addParkingStatus = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.sensoris.protobuf.categories.drivingbehavior.ParkingStatus, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory} returns this
 */
proto.sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory.prototype.clearParkingStatusList = function() {
  return this.setParkingStatusList([]);
};


goog.object.extend(exports, proto.sensoris.protobuf.categories.drivingbehavior);
