// source: sensoris/protobuf/categories/localization.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var sensoris_protobuf_types_base_pb = require('../../../sensoris/protobuf/types/base_pb.js');
goog.object.extend(proto, sensoris_protobuf_types_base_pb);
var sensoris_protobuf_types_spatial_pb = require('../../../sensoris/protobuf/types/spatial_pb.js');
goog.object.extend(proto, sensoris_protobuf_types_spatial_pb);
goog.exportSymbol('proto.sensoris.protobuf.categories.localization.LocalizationCategory', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.localization.VehicleAcceleration', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.localization.VehicleOdometry', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.FixType', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.localization.VehicleRotationRate', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.localization.VehicleSpeed', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.displayName = 'proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.displayName = 'proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensoris.protobuf.categories.localization.VehicleOdometry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.localization.VehicleOdometry.displayName = 'proto.sensoris.protobuf.categories.localization.VehicleOdometry';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.localization.VehicleSpeed = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensoris.protobuf.categories.localization.VehicleSpeed, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.localization.VehicleSpeed.displayName = 'proto.sensoris.protobuf.categories.localization.VehicleSpeed';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.localization.VehicleAcceleration = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensoris.protobuf.categories.localization.VehicleAcceleration, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.localization.VehicleAcceleration.displayName = 'proto.sensoris.protobuf.categories.localization.VehicleAcceleration';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.localization.VehicleRotationRate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensoris.protobuf.categories.localization.VehicleRotationRate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.localization.VehicleRotationRate.displayName = 'proto.sensoris.protobuf.categories.localization.VehicleRotationRate';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sensoris.protobuf.categories.localization.LocalizationCategory.repeatedFields_, null);
};
goog.inherits(proto.sensoris.protobuf.categories.localization.LocalizationCategory, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.localization.LocalizationCategory.displayName = 'proto.sensoris.protobuf.categories.localization.LocalizationCategory';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.toObject = function(includeInstance, msg) {
  var f, obj = {
    envelope: (f = msg.getEnvelope()) && sensoris_protobuf_types_base_pb.EventEnvelope.toObject(includeInstance, f),
    positionAndAccuracy: (f = msg.getPositionAndAccuracy()) && sensoris_protobuf_types_spatial_pb.PositionAndAccuracy.toObject(includeInstance, f),
    orientationAndAccuracy: (f = msg.getOrientationAndAccuracy()) && sensoris_protobuf_types_spatial_pb.RotationAndAccuracy.toObject(includeInstance, f),
    navigationSatelliteSystemStatus: (f = msg.getNavigationSatelliteSystemStatus()) && proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation;
  return proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new sensoris_protobuf_types_base_pb.EventEnvelope;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.EventEnvelope.deserializeBinaryFromReader);
      msg.setEnvelope(value);
      break;
    case 2:
      var value = new sensoris_protobuf_types_spatial_pb.PositionAndAccuracy;
      reader.readMessage(value,sensoris_protobuf_types_spatial_pb.PositionAndAccuracy.deserializeBinaryFromReader);
      msg.setPositionAndAccuracy(value);
      break;
    case 3:
      var value = new sensoris_protobuf_types_spatial_pb.RotationAndAccuracy;
      reader.readMessage(value,sensoris_protobuf_types_spatial_pb.RotationAndAccuracy.deserializeBinaryFromReader);
      msg.setOrientationAndAccuracy(value);
      break;
    case 4:
      var value = new proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus;
      reader.readMessage(value,proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.deserializeBinaryFromReader);
      msg.setNavigationSatelliteSystemStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvelope();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      sensoris_protobuf_types_base_pb.EventEnvelope.serializeBinaryToWriter
    );
  }
  f = message.getPositionAndAccuracy();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      sensoris_protobuf_types_spatial_pb.PositionAndAccuracy.serializeBinaryToWriter
    );
  }
  f = message.getOrientationAndAccuracy();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      sensoris_protobuf_types_spatial_pb.RotationAndAccuracy.serializeBinaryToWriter
    );
  }
  f = message.getNavigationSatelliteSystemStatus();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    fixType: jspb.Message.getFieldWithDefault(msg, 1, 0),
    count: (f = msg.getCount()) && sensoris_protobuf_types_base_pb.Int64Value.toObject(includeInstance, f),
    hdop: (f = msg.getHdop()) && sensoris_protobuf_types_base_pb.Int64Value.toObject(includeInstance, f),
    vdop: (f = msg.getVdop()) && sensoris_protobuf_types_base_pb.Int64Value.toObject(includeInstance, f),
    pdop: (f = msg.getPdop()) && sensoris_protobuf_types_base_pb.Int64Value.toObject(includeInstance, f),
    tdop: (f = msg.getTdop()) && sensoris_protobuf_types_base_pb.Int64Value.toObject(includeInstance, f),
    snr: (f = msg.getSnr()) && sensoris_protobuf_types_base_pb.Int64Value.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus;
  return proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.FixType} */ (reader.readEnum());
      msg.setFixType(value);
      break;
    case 2:
      var value = new sensoris_protobuf_types_base_pb.Int64Value;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.Int64Value.deserializeBinaryFromReader);
      msg.setCount(value);
      break;
    case 3:
      var value = new sensoris_protobuf_types_base_pb.Int64Value;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.Int64Value.deserializeBinaryFromReader);
      msg.setHdop(value);
      break;
    case 4:
      var value = new sensoris_protobuf_types_base_pb.Int64Value;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.Int64Value.deserializeBinaryFromReader);
      msg.setVdop(value);
      break;
    case 5:
      var value = new sensoris_protobuf_types_base_pb.Int64Value;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.Int64Value.deserializeBinaryFromReader);
      msg.setPdop(value);
      break;
    case 6:
      var value = new sensoris_protobuf_types_base_pb.Int64Value;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTdop(value);
      break;
    case 8:
      var value = new sensoris_protobuf_types_base_pb.Int64Value;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.Int64Value.deserializeBinaryFromReader);
      msg.setSnr(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFixType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getCount();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      sensoris_protobuf_types_base_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getHdop();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      sensoris_protobuf_types_base_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getVdop();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      sensoris_protobuf_types_base_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getPdop();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      sensoris_protobuf_types_base_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTdop();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      sensoris_protobuf_types_base_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getSnr();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      sensoris_protobuf_types_base_pb.Int64Value.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.FixType = {
  UNKNOWN_FIX_TYPE: 0,
  NONE: 1,
  TWO_D: 2,
  TWO_D_SATELLITE_BASED_AUGMENTATION: 3,
  TWO_D_GROUND_BASED_AUGMENTATION: 4,
  TWO_D_SATELLITE_AND_GROUND_BASED_AUGMENTATION: 5,
  THREE_D: 6,
  THREE_D_SATELLITE_BASED_AUGMENTATION: 7,
  THREE_D_GROUND_BASED_AUGMENTATION: 8,
  THREE_D_SATELLITE_AND_GROUND_BASED_AUGMENTATION: 9
};

/**
 * optional FixType fix_type = 1;
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.FixType}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.getFixType = function() {
  return /** @type {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.FixType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.FixType} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus} returns this
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.setFixType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional sensoris.protobuf.types.base.Int64Value count = 2;
 * @return {?proto.sensoris.protobuf.types.base.Int64Value}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.getCount = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.Int64Value} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.Int64Value, 2));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.Int64Value|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus} returns this
*/
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.setCount = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus} returns this
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.clearCount = function() {
  return this.setCount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.hasCount = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional sensoris.protobuf.types.base.Int64Value hdop = 3;
 * @return {?proto.sensoris.protobuf.types.base.Int64Value}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.getHdop = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.Int64Value} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.Int64Value, 3));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.Int64Value|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus} returns this
*/
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.setHdop = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus} returns this
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.clearHdop = function() {
  return this.setHdop(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.hasHdop = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional sensoris.protobuf.types.base.Int64Value vdop = 4;
 * @return {?proto.sensoris.protobuf.types.base.Int64Value}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.getVdop = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.Int64Value} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.Int64Value, 4));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.Int64Value|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus} returns this
*/
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.setVdop = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus} returns this
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.clearVdop = function() {
  return this.setVdop(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.hasVdop = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional sensoris.protobuf.types.base.Int64Value pdop = 5;
 * @return {?proto.sensoris.protobuf.types.base.Int64Value}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.getPdop = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.Int64Value} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.Int64Value, 5));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.Int64Value|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus} returns this
*/
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.setPdop = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus} returns this
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.clearPdop = function() {
  return this.setPdop(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.hasPdop = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional sensoris.protobuf.types.base.Int64Value tdop = 6;
 * @return {?proto.sensoris.protobuf.types.base.Int64Value}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.getTdop = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.Int64Value} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.Int64Value, 6));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.Int64Value|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus} returns this
*/
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.setTdop = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus} returns this
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.clearTdop = function() {
  return this.setTdop(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.hasTdop = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional sensoris.protobuf.types.base.Int64Value snr = 8;
 * @return {?proto.sensoris.protobuf.types.base.Int64Value}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.getSnr = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.Int64Value} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.Int64Value, 8));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.Int64Value|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus} returns this
*/
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.setSnr = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus} returns this
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.clearSnr = function() {
  return this.setSnr(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus.prototype.hasSnr = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional sensoris.protobuf.types.base.EventEnvelope envelope = 1;
 * @return {?proto.sensoris.protobuf.types.base.EventEnvelope}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.getEnvelope = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.EventEnvelope} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.EventEnvelope, 1));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.EventEnvelope|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation} returns this
*/
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.setEnvelope = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation} returns this
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.clearEnvelope = function() {
  return this.setEnvelope(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.hasEnvelope = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional sensoris.protobuf.types.spatial.PositionAndAccuracy position_and_accuracy = 2;
 * @return {?proto.sensoris.protobuf.types.spatial.PositionAndAccuracy}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.getPositionAndAccuracy = function() {
  return /** @type{?proto.sensoris.protobuf.types.spatial.PositionAndAccuracy} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_spatial_pb.PositionAndAccuracy, 2));
};


/**
 * @param {?proto.sensoris.protobuf.types.spatial.PositionAndAccuracy|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation} returns this
*/
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.setPositionAndAccuracy = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation} returns this
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.clearPositionAndAccuracy = function() {
  return this.setPositionAndAccuracy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.hasPositionAndAccuracy = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional sensoris.protobuf.types.spatial.RotationAndAccuracy orientation_and_accuracy = 3;
 * @return {?proto.sensoris.protobuf.types.spatial.RotationAndAccuracy}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.getOrientationAndAccuracy = function() {
  return /** @type{?proto.sensoris.protobuf.types.spatial.RotationAndAccuracy} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_spatial_pb.RotationAndAccuracy, 3));
};


/**
 * @param {?proto.sensoris.protobuf.types.spatial.RotationAndAccuracy|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation} returns this
*/
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.setOrientationAndAccuracy = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation} returns this
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.clearOrientationAndAccuracy = function() {
  return this.setOrientationAndAccuracy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.hasOrientationAndAccuracy = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional NavigationSatelliteSystemStatus navigation_satellite_system_status = 4;
 * @return {?proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.getNavigationSatelliteSystemStatus = function() {
  return /** @type{?proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus} */ (
    jspb.Message.getWrapperField(this, proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus, 4));
};


/**
 * @param {?proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.NavigationSatelliteSystemStatus|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation} returns this
*/
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.setNavigationSatelliteSystemStatus = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation} returns this
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.clearNavigationSatelliteSystemStatus = function() {
  return this.setNavigationSatelliteSystemStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.prototype.hasNavigationSatelliteSystemStatus = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.localization.VehicleOdometry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.localization.VehicleOdometry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.toObject = function(includeInstance, msg) {
  var f, obj = {
    envelope: (f = msg.getEnvelope()) && sensoris_protobuf_types_base_pb.EventEnvelope.toObject(includeInstance, f),
    endTimestamp: (f = msg.getEndTimestamp()) && sensoris_protobuf_types_base_pb.Timestamp.toObject(includeInstance, f),
    translationAndAccuracy: (f = msg.getTranslationAndAccuracy()) && sensoris_protobuf_types_spatial_pb.PositionAndAccuracy.toObject(includeInstance, f),
    rotationAndAccuracy: (f = msg.getRotationAndAccuracy()) && sensoris_protobuf_types_spatial_pb.RotationAndAccuracy.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleOdometry}
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.localization.VehicleOdometry;
  return proto.sensoris.protobuf.categories.localization.VehicleOdometry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.localization.VehicleOdometry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleOdometry}
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new sensoris_protobuf_types_base_pb.EventEnvelope;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.EventEnvelope.deserializeBinaryFromReader);
      msg.setEnvelope(value);
      break;
    case 2:
      var value = new sensoris_protobuf_types_base_pb.Timestamp;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEndTimestamp(value);
      break;
    case 3:
      var value = new sensoris_protobuf_types_spatial_pb.PositionAndAccuracy;
      reader.readMessage(value,sensoris_protobuf_types_spatial_pb.PositionAndAccuracy.deserializeBinaryFromReader);
      msg.setTranslationAndAccuracy(value);
      break;
    case 4:
      var value = new sensoris_protobuf_types_spatial_pb.RotationAndAccuracy;
      reader.readMessage(value,sensoris_protobuf_types_spatial_pb.RotationAndAccuracy.deserializeBinaryFromReader);
      msg.setRotationAndAccuracy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.localization.VehicleOdometry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.localization.VehicleOdometry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvelope();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      sensoris_protobuf_types_base_pb.EventEnvelope.serializeBinaryToWriter
    );
  }
  f = message.getEndTimestamp();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      sensoris_protobuf_types_base_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getTranslationAndAccuracy();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      sensoris_protobuf_types_spatial_pb.PositionAndAccuracy.serializeBinaryToWriter
    );
  }
  f = message.getRotationAndAccuracy();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      sensoris_protobuf_types_spatial_pb.RotationAndAccuracy.serializeBinaryToWriter
    );
  }
};


/**
 * optional sensoris.protobuf.types.base.EventEnvelope envelope = 1;
 * @return {?proto.sensoris.protobuf.types.base.EventEnvelope}
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.getEnvelope = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.EventEnvelope} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.EventEnvelope, 1));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.EventEnvelope|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleOdometry} returns this
*/
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.setEnvelope = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleOdometry} returns this
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.clearEnvelope = function() {
  return this.setEnvelope(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.hasEnvelope = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional sensoris.protobuf.types.base.Timestamp end_timestamp = 2;
 * @return {?proto.sensoris.protobuf.types.base.Timestamp}
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.getEndTimestamp = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.Timestamp} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.Timestamp, 2));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.Timestamp|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleOdometry} returns this
*/
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.setEndTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleOdometry} returns this
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.clearEndTimestamp = function() {
  return this.setEndTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.hasEndTimestamp = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional sensoris.protobuf.types.spatial.PositionAndAccuracy translation_and_accuracy = 3;
 * @return {?proto.sensoris.protobuf.types.spatial.PositionAndAccuracy}
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.getTranslationAndAccuracy = function() {
  return /** @type{?proto.sensoris.protobuf.types.spatial.PositionAndAccuracy} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_spatial_pb.PositionAndAccuracy, 3));
};


/**
 * @param {?proto.sensoris.protobuf.types.spatial.PositionAndAccuracy|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleOdometry} returns this
*/
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.setTranslationAndAccuracy = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleOdometry} returns this
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.clearTranslationAndAccuracy = function() {
  return this.setTranslationAndAccuracy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.hasTranslationAndAccuracy = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional sensoris.protobuf.types.spatial.RotationAndAccuracy rotation_and_accuracy = 4;
 * @return {?proto.sensoris.protobuf.types.spatial.RotationAndAccuracy}
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.getRotationAndAccuracy = function() {
  return /** @type{?proto.sensoris.protobuf.types.spatial.RotationAndAccuracy} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_spatial_pb.RotationAndAccuracy, 4));
};


/**
 * @param {?proto.sensoris.protobuf.types.spatial.RotationAndAccuracy|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleOdometry} returns this
*/
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.setRotationAndAccuracy = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleOdometry} returns this
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.clearRotationAndAccuracy = function() {
  return this.setRotationAndAccuracy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehicleOdometry.prototype.hasRotationAndAccuracy = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.localization.VehicleSpeed.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.localization.VehicleSpeed.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.localization.VehicleSpeed} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.localization.VehicleSpeed.toObject = function(includeInstance, msg) {
  var f, obj = {
    envelope: (f = msg.getEnvelope()) && sensoris_protobuf_types_base_pb.EventEnvelope.toObject(includeInstance, f),
    valueAndAccuracy: (f = msg.getValueAndAccuracy()) && sensoris_protobuf_types_spatial_pb.XyzVectorAndAccuracy.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleSpeed}
 */
proto.sensoris.protobuf.categories.localization.VehicleSpeed.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.localization.VehicleSpeed;
  return proto.sensoris.protobuf.categories.localization.VehicleSpeed.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.localization.VehicleSpeed} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleSpeed}
 */
proto.sensoris.protobuf.categories.localization.VehicleSpeed.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new sensoris_protobuf_types_base_pb.EventEnvelope;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.EventEnvelope.deserializeBinaryFromReader);
      msg.setEnvelope(value);
      break;
    case 2:
      var value = new sensoris_protobuf_types_spatial_pb.XyzVectorAndAccuracy;
      reader.readMessage(value,sensoris_protobuf_types_spatial_pb.XyzVectorAndAccuracy.deserializeBinaryFromReader);
      msg.setValueAndAccuracy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.localization.VehicleSpeed.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.localization.VehicleSpeed.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.localization.VehicleSpeed} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.localization.VehicleSpeed.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvelope();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      sensoris_protobuf_types_base_pb.EventEnvelope.serializeBinaryToWriter
    );
  }
  f = message.getValueAndAccuracy();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      sensoris_protobuf_types_spatial_pb.XyzVectorAndAccuracy.serializeBinaryToWriter
    );
  }
};


/**
 * optional sensoris.protobuf.types.base.EventEnvelope envelope = 1;
 * @return {?proto.sensoris.protobuf.types.base.EventEnvelope}
 */
proto.sensoris.protobuf.categories.localization.VehicleSpeed.prototype.getEnvelope = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.EventEnvelope} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.EventEnvelope, 1));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.EventEnvelope|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleSpeed} returns this
*/
proto.sensoris.protobuf.categories.localization.VehicleSpeed.prototype.setEnvelope = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleSpeed} returns this
 */
proto.sensoris.protobuf.categories.localization.VehicleSpeed.prototype.clearEnvelope = function() {
  return this.setEnvelope(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehicleSpeed.prototype.hasEnvelope = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional sensoris.protobuf.types.spatial.XyzVectorAndAccuracy value_and_accuracy = 2;
 * @return {?proto.sensoris.protobuf.types.spatial.XyzVectorAndAccuracy}
 */
proto.sensoris.protobuf.categories.localization.VehicleSpeed.prototype.getValueAndAccuracy = function() {
  return /** @type{?proto.sensoris.protobuf.types.spatial.XyzVectorAndAccuracy} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_spatial_pb.XyzVectorAndAccuracy, 2));
};


/**
 * @param {?proto.sensoris.protobuf.types.spatial.XyzVectorAndAccuracy|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleSpeed} returns this
*/
proto.sensoris.protobuf.categories.localization.VehicleSpeed.prototype.setValueAndAccuracy = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleSpeed} returns this
 */
proto.sensoris.protobuf.categories.localization.VehicleSpeed.prototype.clearValueAndAccuracy = function() {
  return this.setValueAndAccuracy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehicleSpeed.prototype.hasValueAndAccuracy = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.localization.VehicleAcceleration.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.localization.VehicleAcceleration.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.localization.VehicleAcceleration} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.localization.VehicleAcceleration.toObject = function(includeInstance, msg) {
  var f, obj = {
    envelope: (f = msg.getEnvelope()) && sensoris_protobuf_types_base_pb.EventEnvelope.toObject(includeInstance, f),
    valueAndAccuracy: (f = msg.getValueAndAccuracy()) && sensoris_protobuf_types_spatial_pb.XyzVectorAndAccuracy.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleAcceleration}
 */
proto.sensoris.protobuf.categories.localization.VehicleAcceleration.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.localization.VehicleAcceleration;
  return proto.sensoris.protobuf.categories.localization.VehicleAcceleration.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.localization.VehicleAcceleration} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleAcceleration}
 */
proto.sensoris.protobuf.categories.localization.VehicleAcceleration.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new sensoris_protobuf_types_base_pb.EventEnvelope;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.EventEnvelope.deserializeBinaryFromReader);
      msg.setEnvelope(value);
      break;
    case 2:
      var value = new sensoris_protobuf_types_spatial_pb.XyzVectorAndAccuracy;
      reader.readMessage(value,sensoris_protobuf_types_spatial_pb.XyzVectorAndAccuracy.deserializeBinaryFromReader);
      msg.setValueAndAccuracy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.localization.VehicleAcceleration.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.localization.VehicleAcceleration.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.localization.VehicleAcceleration} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.localization.VehicleAcceleration.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvelope();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      sensoris_protobuf_types_base_pb.EventEnvelope.serializeBinaryToWriter
    );
  }
  f = message.getValueAndAccuracy();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      sensoris_protobuf_types_spatial_pb.XyzVectorAndAccuracy.serializeBinaryToWriter
    );
  }
};


/**
 * optional sensoris.protobuf.types.base.EventEnvelope envelope = 1;
 * @return {?proto.sensoris.protobuf.types.base.EventEnvelope}
 */
proto.sensoris.protobuf.categories.localization.VehicleAcceleration.prototype.getEnvelope = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.EventEnvelope} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.EventEnvelope, 1));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.EventEnvelope|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleAcceleration} returns this
*/
proto.sensoris.protobuf.categories.localization.VehicleAcceleration.prototype.setEnvelope = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleAcceleration} returns this
 */
proto.sensoris.protobuf.categories.localization.VehicleAcceleration.prototype.clearEnvelope = function() {
  return this.setEnvelope(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehicleAcceleration.prototype.hasEnvelope = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional sensoris.protobuf.types.spatial.XyzVectorAndAccuracy value_and_accuracy = 2;
 * @return {?proto.sensoris.protobuf.types.spatial.XyzVectorAndAccuracy}
 */
proto.sensoris.protobuf.categories.localization.VehicleAcceleration.prototype.getValueAndAccuracy = function() {
  return /** @type{?proto.sensoris.protobuf.types.spatial.XyzVectorAndAccuracy} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_spatial_pb.XyzVectorAndAccuracy, 2));
};


/**
 * @param {?proto.sensoris.protobuf.types.spatial.XyzVectorAndAccuracy|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleAcceleration} returns this
*/
proto.sensoris.protobuf.categories.localization.VehicleAcceleration.prototype.setValueAndAccuracy = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleAcceleration} returns this
 */
proto.sensoris.protobuf.categories.localization.VehicleAcceleration.prototype.clearValueAndAccuracy = function() {
  return this.setValueAndAccuracy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehicleAcceleration.prototype.hasValueAndAccuracy = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.localization.VehicleRotationRate.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.localization.VehicleRotationRate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.localization.VehicleRotationRate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.localization.VehicleRotationRate.toObject = function(includeInstance, msg) {
  var f, obj = {
    envelope: (f = msg.getEnvelope()) && sensoris_protobuf_types_base_pb.EventEnvelope.toObject(includeInstance, f),
    valueAndAccuracy: (f = msg.getValueAndAccuracy()) && sensoris_protobuf_types_spatial_pb.RotationRateAndAccuracy.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleRotationRate}
 */
proto.sensoris.protobuf.categories.localization.VehicleRotationRate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.localization.VehicleRotationRate;
  return proto.sensoris.protobuf.categories.localization.VehicleRotationRate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.localization.VehicleRotationRate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleRotationRate}
 */
proto.sensoris.protobuf.categories.localization.VehicleRotationRate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new sensoris_protobuf_types_base_pb.EventEnvelope;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.EventEnvelope.deserializeBinaryFromReader);
      msg.setEnvelope(value);
      break;
    case 2:
      var value = new sensoris_protobuf_types_spatial_pb.RotationRateAndAccuracy;
      reader.readMessage(value,sensoris_protobuf_types_spatial_pb.RotationRateAndAccuracy.deserializeBinaryFromReader);
      msg.setValueAndAccuracy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.localization.VehicleRotationRate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.localization.VehicleRotationRate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.localization.VehicleRotationRate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.localization.VehicleRotationRate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvelope();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      sensoris_protobuf_types_base_pb.EventEnvelope.serializeBinaryToWriter
    );
  }
  f = message.getValueAndAccuracy();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      sensoris_protobuf_types_spatial_pb.RotationRateAndAccuracy.serializeBinaryToWriter
    );
  }
};


/**
 * optional sensoris.protobuf.types.base.EventEnvelope envelope = 1;
 * @return {?proto.sensoris.protobuf.types.base.EventEnvelope}
 */
proto.sensoris.protobuf.categories.localization.VehicleRotationRate.prototype.getEnvelope = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.EventEnvelope} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.EventEnvelope, 1));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.EventEnvelope|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleRotationRate} returns this
*/
proto.sensoris.protobuf.categories.localization.VehicleRotationRate.prototype.setEnvelope = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleRotationRate} returns this
 */
proto.sensoris.protobuf.categories.localization.VehicleRotationRate.prototype.clearEnvelope = function() {
  return this.setEnvelope(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehicleRotationRate.prototype.hasEnvelope = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional sensoris.protobuf.types.spatial.RotationRateAndAccuracy value_and_accuracy = 2;
 * @return {?proto.sensoris.protobuf.types.spatial.RotationRateAndAccuracy}
 */
proto.sensoris.protobuf.categories.localization.VehicleRotationRate.prototype.getValueAndAccuracy = function() {
  return /** @type{?proto.sensoris.protobuf.types.spatial.RotationRateAndAccuracy} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_spatial_pb.RotationRateAndAccuracy, 2));
};


/**
 * @param {?proto.sensoris.protobuf.types.spatial.RotationRateAndAccuracy|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleRotationRate} returns this
*/
proto.sensoris.protobuf.categories.localization.VehicleRotationRate.prototype.setValueAndAccuracy = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleRotationRate} returns this
 */
proto.sensoris.protobuf.categories.localization.VehicleRotationRate.prototype.clearValueAndAccuracy = function() {
  return this.setValueAndAccuracy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.VehicleRotationRate.prototype.hasValueAndAccuracy = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.repeatedFields_ = [2,3,4,5,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.localization.LocalizationCategory.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.localization.LocalizationCategory} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.toObject = function(includeInstance, msg) {
  var f, obj = {
    envelope: (f = msg.getEnvelope()) && sensoris_protobuf_types_base_pb.CategoryEnvelope.toObject(includeInstance, f),
    vehiclePositionAndOrientationList: jspb.Message.toObjectList(msg.getVehiclePositionAndOrientationList(),
    proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.toObject, includeInstance),
    vehicleOdometryList: jspb.Message.toObjectList(msg.getVehicleOdometryList(),
    proto.sensoris.protobuf.categories.localization.VehicleOdometry.toObject, includeInstance),
    vehicleSpeedList: jspb.Message.toObjectList(msg.getVehicleSpeedList(),
    proto.sensoris.protobuf.categories.localization.VehicleSpeed.toObject, includeInstance),
    vehicleAccelerationList: jspb.Message.toObjectList(msg.getVehicleAccelerationList(),
    proto.sensoris.protobuf.categories.localization.VehicleAcceleration.toObject, includeInstance),
    vehicleRotationRateList: jspb.Message.toObjectList(msg.getVehicleRotationRateList(),
    proto.sensoris.protobuf.categories.localization.VehicleRotationRate.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.localization.LocalizationCategory}
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.localization.LocalizationCategory;
  return proto.sensoris.protobuf.categories.localization.LocalizationCategory.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.localization.LocalizationCategory} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.localization.LocalizationCategory}
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new sensoris_protobuf_types_base_pb.CategoryEnvelope;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.CategoryEnvelope.deserializeBinaryFromReader);
      msg.setEnvelope(value);
      break;
    case 2:
      var value = new proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation;
      reader.readMessage(value,proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.deserializeBinaryFromReader);
      msg.addVehiclePositionAndOrientation(value);
      break;
    case 3:
      var value = new proto.sensoris.protobuf.categories.localization.VehicleOdometry;
      reader.readMessage(value,proto.sensoris.protobuf.categories.localization.VehicleOdometry.deserializeBinaryFromReader);
      msg.addVehicleOdometry(value);
      break;
    case 4:
      var value = new proto.sensoris.protobuf.categories.localization.VehicleSpeed;
      reader.readMessage(value,proto.sensoris.protobuf.categories.localization.VehicleSpeed.deserializeBinaryFromReader);
      msg.addVehicleSpeed(value);
      break;
    case 5:
      var value = new proto.sensoris.protobuf.categories.localization.VehicleAcceleration;
      reader.readMessage(value,proto.sensoris.protobuf.categories.localization.VehicleAcceleration.deserializeBinaryFromReader);
      msg.addVehicleAcceleration(value);
      break;
    case 6:
      var value = new proto.sensoris.protobuf.categories.localization.VehicleRotationRate;
      reader.readMessage(value,proto.sensoris.protobuf.categories.localization.VehicleRotationRate.deserializeBinaryFromReader);
      msg.addVehicleRotationRate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.localization.LocalizationCategory.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.localization.LocalizationCategory} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvelope();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      sensoris_protobuf_types_base_pb.CategoryEnvelope.serializeBinaryToWriter
    );
  }
  f = message.getVehiclePositionAndOrientationList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation.serializeBinaryToWriter
    );
  }
  f = message.getVehicleOdometryList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.sensoris.protobuf.categories.localization.VehicleOdometry.serializeBinaryToWriter
    );
  }
  f = message.getVehicleSpeedList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.sensoris.protobuf.categories.localization.VehicleSpeed.serializeBinaryToWriter
    );
  }
  f = message.getVehicleAccelerationList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.sensoris.protobuf.categories.localization.VehicleAcceleration.serializeBinaryToWriter
    );
  }
  f = message.getVehicleRotationRateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.sensoris.protobuf.categories.localization.VehicleRotationRate.serializeBinaryToWriter
    );
  }
};


/**
 * optional sensoris.protobuf.types.base.CategoryEnvelope envelope = 1;
 * @return {?proto.sensoris.protobuf.types.base.CategoryEnvelope}
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.getEnvelope = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.CategoryEnvelope} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.CategoryEnvelope, 1));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.CategoryEnvelope|undefined} value
 * @return {!proto.sensoris.protobuf.categories.localization.LocalizationCategory} returns this
*/
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.setEnvelope = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.localization.LocalizationCategory} returns this
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.clearEnvelope = function() {
  return this.setEnvelope(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.hasEnvelope = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated VehiclePositionAndOrientation vehicle_position_and_orientation = 2;
 * @return {!Array<!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation>}
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.getVehiclePositionAndOrientationList = function() {
  return /** @type{!Array<!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation, 2));
};


/**
 * @param {!Array<!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation>} value
 * @return {!proto.sensoris.protobuf.categories.localization.LocalizationCategory} returns this
*/
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.setVehiclePositionAndOrientationList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation}
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.addVehiclePositionAndOrientation = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.sensoris.protobuf.categories.localization.VehiclePositionAndOrientation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sensoris.protobuf.categories.localization.LocalizationCategory} returns this
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.clearVehiclePositionAndOrientationList = function() {
  return this.setVehiclePositionAndOrientationList([]);
};


/**
 * repeated VehicleOdometry vehicle_odometry = 3;
 * @return {!Array<!proto.sensoris.protobuf.categories.localization.VehicleOdometry>}
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.getVehicleOdometryList = function() {
  return /** @type{!Array<!proto.sensoris.protobuf.categories.localization.VehicleOdometry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sensoris.protobuf.categories.localization.VehicleOdometry, 3));
};


/**
 * @param {!Array<!proto.sensoris.protobuf.categories.localization.VehicleOdometry>} value
 * @return {!proto.sensoris.protobuf.categories.localization.LocalizationCategory} returns this
*/
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.setVehicleOdometryList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.sensoris.protobuf.categories.localization.VehicleOdometry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleOdometry}
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.addVehicleOdometry = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.sensoris.protobuf.categories.localization.VehicleOdometry, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sensoris.protobuf.categories.localization.LocalizationCategory} returns this
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.clearVehicleOdometryList = function() {
  return this.setVehicleOdometryList([]);
};


/**
 * repeated VehicleSpeed vehicle_speed = 4;
 * @return {!Array<!proto.sensoris.protobuf.categories.localization.VehicleSpeed>}
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.getVehicleSpeedList = function() {
  return /** @type{!Array<!proto.sensoris.protobuf.categories.localization.VehicleSpeed>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sensoris.protobuf.categories.localization.VehicleSpeed, 4));
};


/**
 * @param {!Array<!proto.sensoris.protobuf.categories.localization.VehicleSpeed>} value
 * @return {!proto.sensoris.protobuf.categories.localization.LocalizationCategory} returns this
*/
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.setVehicleSpeedList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.sensoris.protobuf.categories.localization.VehicleSpeed=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleSpeed}
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.addVehicleSpeed = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.sensoris.protobuf.categories.localization.VehicleSpeed, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sensoris.protobuf.categories.localization.LocalizationCategory} returns this
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.clearVehicleSpeedList = function() {
  return this.setVehicleSpeedList([]);
};


/**
 * repeated VehicleAcceleration vehicle_acceleration = 5;
 * @return {!Array<!proto.sensoris.protobuf.categories.localization.VehicleAcceleration>}
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.getVehicleAccelerationList = function() {
  return /** @type{!Array<!proto.sensoris.protobuf.categories.localization.VehicleAcceleration>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sensoris.protobuf.categories.localization.VehicleAcceleration, 5));
};


/**
 * @param {!Array<!proto.sensoris.protobuf.categories.localization.VehicleAcceleration>} value
 * @return {!proto.sensoris.protobuf.categories.localization.LocalizationCategory} returns this
*/
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.setVehicleAccelerationList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.sensoris.protobuf.categories.localization.VehicleAcceleration=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleAcceleration}
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.addVehicleAcceleration = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.sensoris.protobuf.categories.localization.VehicleAcceleration, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sensoris.protobuf.categories.localization.LocalizationCategory} returns this
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.clearVehicleAccelerationList = function() {
  return this.setVehicleAccelerationList([]);
};


/**
 * repeated VehicleRotationRate vehicle_rotation_rate = 6;
 * @return {!Array<!proto.sensoris.protobuf.categories.localization.VehicleRotationRate>}
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.getVehicleRotationRateList = function() {
  return /** @type{!Array<!proto.sensoris.protobuf.categories.localization.VehicleRotationRate>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sensoris.protobuf.categories.localization.VehicleRotationRate, 6));
};


/**
 * @param {!Array<!proto.sensoris.protobuf.categories.localization.VehicleRotationRate>} value
 * @return {!proto.sensoris.protobuf.categories.localization.LocalizationCategory} returns this
*/
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.setVehicleRotationRateList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.sensoris.protobuf.categories.localization.VehicleRotationRate=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sensoris.protobuf.categories.localization.VehicleRotationRate}
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.addVehicleRotationRate = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.sensoris.protobuf.categories.localization.VehicleRotationRate, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sensoris.protobuf.categories.localization.LocalizationCategory} returns this
 */
proto.sensoris.protobuf.categories.localization.LocalizationCategory.prototype.clearVehicleRotationRateList = function() {
  return this.setVehicleRotationRateList([]);
};


goog.object.extend(exports, proto.sensoris.protobuf.categories.localization);
