// source: sensoris/protobuf/categories/powertrain.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var sensoris_protobuf_types_base_pb = require('../../../sensoris/protobuf/types/base_pb.js');
goog.object.extend(proto, sensoris_protobuf_types_base_pb);
goog.exportSymbol('proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.Type', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.powertrain.EngineStatus', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.powertrain.EngineStatus.IgnitionStatus', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.powertrain.EngineStatus.PowertrainStatus', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.powertrain.PowertrainCategory', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.powertrain.TransmissionStatus', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.DriveMode', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.GearMode', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.powertrain.EngineStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensoris.protobuf.categories.powertrain.EngineStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.powertrain.EngineStatus.displayName = 'proto.sensoris.protobuf.categories.powertrain.EngineStatus';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensoris.protobuf.categories.powertrain.TransmissionStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.displayName = 'proto.sensoris.protobuf.categories.powertrain.TransmissionStatus';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.displayName = 'proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.repeatedFields_, null);
};
goog.inherits(proto.sensoris.protobuf.categories.powertrain.PowertrainCategory, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.displayName = 'proto.sensoris.protobuf.categories.powertrain.PowertrainCategory';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.powertrain.EngineStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.powertrain.EngineStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.powertrain.EngineStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.powertrain.EngineStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    envelope: (f = msg.getEnvelope()) && sensoris_protobuf_types_base_pb.EventEnvelope.toObject(includeInstance, f),
    ignitionStatus: jspb.Message.getFieldWithDefault(msg, 2, 0),
    powertrainStatus: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.powertrain.EngineStatus}
 */
proto.sensoris.protobuf.categories.powertrain.EngineStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.powertrain.EngineStatus;
  return proto.sensoris.protobuf.categories.powertrain.EngineStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.powertrain.EngineStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.powertrain.EngineStatus}
 */
proto.sensoris.protobuf.categories.powertrain.EngineStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new sensoris_protobuf_types_base_pb.EventEnvelope;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.EventEnvelope.deserializeBinaryFromReader);
      msg.setEnvelope(value);
      break;
    case 2:
      var value = /** @type {!proto.sensoris.protobuf.categories.powertrain.EngineStatus.IgnitionStatus} */ (reader.readEnum());
      msg.setIgnitionStatus(value);
      break;
    case 3:
      var value = /** @type {!proto.sensoris.protobuf.categories.powertrain.EngineStatus.PowertrainStatus} */ (reader.readEnum());
      msg.setPowertrainStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.powertrain.EngineStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.powertrain.EngineStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.powertrain.EngineStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.powertrain.EngineStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvelope();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      sensoris_protobuf_types_base_pb.EventEnvelope.serializeBinaryToWriter
    );
  }
  f = message.getIgnitionStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getPowertrainStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.sensoris.protobuf.categories.powertrain.EngineStatus.IgnitionStatus = {
  UNKNOWN_IGNITION_STATUS: 0,
  IGNITION_LOCK: 1,
  IGNITION_OFF: 2,
  IGNITION_ACCESSORIES: 3,
  IGNITION_ON: 4,
  IGNITION_START: 5
};

/**
 * @enum {number}
 */
proto.sensoris.protobuf.categories.powertrain.EngineStatus.PowertrainStatus = {
  UNKNOWN_POWERTRAIN_STATUS: 0,
  POWERTRAIN_OFF: 1,
  POWERTRAIN_ECO_MODE: 2,
  POWERTRAIN_READY: 3
};

/**
 * optional sensoris.protobuf.types.base.EventEnvelope envelope = 1;
 * @return {?proto.sensoris.protobuf.types.base.EventEnvelope}
 */
proto.sensoris.protobuf.categories.powertrain.EngineStatus.prototype.getEnvelope = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.EventEnvelope} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.EventEnvelope, 1));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.EventEnvelope|undefined} value
 * @return {!proto.sensoris.protobuf.categories.powertrain.EngineStatus} returns this
*/
proto.sensoris.protobuf.categories.powertrain.EngineStatus.prototype.setEnvelope = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.powertrain.EngineStatus} returns this
 */
proto.sensoris.protobuf.categories.powertrain.EngineStatus.prototype.clearEnvelope = function() {
  return this.setEnvelope(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.powertrain.EngineStatus.prototype.hasEnvelope = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional IgnitionStatus ignition_status = 2;
 * @return {!proto.sensoris.protobuf.categories.powertrain.EngineStatus.IgnitionStatus}
 */
proto.sensoris.protobuf.categories.powertrain.EngineStatus.prototype.getIgnitionStatus = function() {
  return /** @type {!proto.sensoris.protobuf.categories.powertrain.EngineStatus.IgnitionStatus} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.sensoris.protobuf.categories.powertrain.EngineStatus.IgnitionStatus} value
 * @return {!proto.sensoris.protobuf.categories.powertrain.EngineStatus} returns this
 */
proto.sensoris.protobuf.categories.powertrain.EngineStatus.prototype.setIgnitionStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional PowertrainStatus powertrain_status = 3;
 * @return {!proto.sensoris.protobuf.categories.powertrain.EngineStatus.PowertrainStatus}
 */
proto.sensoris.protobuf.categories.powertrain.EngineStatus.prototype.getPowertrainStatus = function() {
  return /** @type {!proto.sensoris.protobuf.categories.powertrain.EngineStatus.PowertrainStatus} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.sensoris.protobuf.categories.powertrain.EngineStatus.PowertrainStatus} value
 * @return {!proto.sensoris.protobuf.categories.powertrain.EngineStatus} returns this
 */
proto.sensoris.protobuf.categories.powertrain.EngineStatus.prototype.setPowertrainStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    envelope: (f = msg.getEnvelope()) && sensoris_protobuf_types_base_pb.EventEnvelope.toObject(includeInstance, f),
    gearMode: jspb.Message.getFieldWithDefault(msg, 2, 0),
    driveMode: jspb.Message.getFieldWithDefault(msg, 3, 0),
    currentGear: (f = msg.getCurrentGear()) && sensoris_protobuf_types_base_pb.Int64Value.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus}
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.powertrain.TransmissionStatus;
  return proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus}
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new sensoris_protobuf_types_base_pb.EventEnvelope;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.EventEnvelope.deserializeBinaryFromReader);
      msg.setEnvelope(value);
      break;
    case 2:
      var value = /** @type {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.GearMode} */ (reader.readEnum());
      msg.setGearMode(value);
      break;
    case 3:
      var value = /** @type {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.DriveMode} */ (reader.readEnum());
      msg.setDriveMode(value);
      break;
    case 4:
      var value = new sensoris_protobuf_types_base_pb.Int64Value;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.Int64Value.deserializeBinaryFromReader);
      msg.setCurrentGear(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvelope();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      sensoris_protobuf_types_base_pb.EventEnvelope.serializeBinaryToWriter
    );
  }
  f = message.getGearMode();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getDriveMode();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getCurrentGear();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      sensoris_protobuf_types_base_pb.Int64Value.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.GearMode = {
  UNKNOWN_GEAR_MODE: 0,
  DRIVE: 1,
  MANUAL: 2,
  REVERSE: 3,
  PARK: 4,
  NEUTRAL: 5
};

/**
 * @enum {number}
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.DriveMode = {
  UNKNOWN_DRIVE_MODE: 0,
  ECO: 1,
  COMFORT: 2,
  SPORT: 3,
  SUPER_SPORT: 4
};

/**
 * optional sensoris.protobuf.types.base.EventEnvelope envelope = 1;
 * @return {?proto.sensoris.protobuf.types.base.EventEnvelope}
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.prototype.getEnvelope = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.EventEnvelope} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.EventEnvelope, 1));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.EventEnvelope|undefined} value
 * @return {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus} returns this
*/
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.prototype.setEnvelope = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus} returns this
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.prototype.clearEnvelope = function() {
  return this.setEnvelope(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.prototype.hasEnvelope = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional GearMode gear_mode = 2;
 * @return {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.GearMode}
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.prototype.getGearMode = function() {
  return /** @type {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.GearMode} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.GearMode} value
 * @return {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus} returns this
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.prototype.setGearMode = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional DriveMode drive_mode = 3;
 * @return {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.DriveMode}
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.prototype.getDriveMode = function() {
  return /** @type {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.DriveMode} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.DriveMode} value
 * @return {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus} returns this
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.prototype.setDriveMode = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional sensoris.protobuf.types.base.Int64Value current_gear = 4;
 * @return {?proto.sensoris.protobuf.types.base.Int64Value}
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.prototype.getCurrentGear = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.Int64Value} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.Int64Value, 4));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.Int64Value|undefined} value
 * @return {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus} returns this
*/
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.prototype.setCurrentGear = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus} returns this
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.prototype.clearCurrentGear = function() {
  return this.setCurrentGear(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.prototype.hasCurrentGear = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    envelope: (f = msg.getEnvelope()) && sensoris_protobuf_types_base_pb.EventEnvelope.toObject(includeInstance, f),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0),
    status: jspb.Message.getFieldWithDefault(msg, 3, 0),
    selectedSpeed: (f = msg.getSelectedSpeed()) && sensoris_protobuf_types_base_pb.Int64Value.toObject(includeInstance, f),
    selectedTimeToLeadVehicle: (f = msg.getSelectedTimeToLeadVehicle()) && sensoris_protobuf_types_base_pb.Int64Value.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus}
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus;
  return proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus}
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new sensoris_protobuf_types_base_pb.EventEnvelope;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.EventEnvelope.deserializeBinaryFromReader);
      msg.setEnvelope(value);
      break;
    case 2:
      var value = /** @type {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {!proto.sensoris.protobuf.types.base.SystemStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 4:
      var value = new sensoris_protobuf_types_base_pb.Int64Value;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.Int64Value.deserializeBinaryFromReader);
      msg.setSelectedSpeed(value);
      break;
    case 5:
      var value = new sensoris_protobuf_types_base_pb.Int64Value;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.Int64Value.deserializeBinaryFromReader);
      msg.setSelectedTimeToLeadVehicle(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvelope();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      sensoris_protobuf_types_base_pb.EventEnvelope.serializeBinaryToWriter
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getSelectedSpeed();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      sensoris_protobuf_types_base_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getSelectedTimeToLeadVehicle();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      sensoris_protobuf_types_base_pb.Int64Value.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.Type = {
  UNKNOWN_TYPE: 0,
  SPEED: 1,
  SPEED_AND_DISTANCE: 2
};

/**
 * optional sensoris.protobuf.types.base.EventEnvelope envelope = 1;
 * @return {?proto.sensoris.protobuf.types.base.EventEnvelope}
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.getEnvelope = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.EventEnvelope} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.EventEnvelope, 1));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.EventEnvelope|undefined} value
 * @return {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus} returns this
*/
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.setEnvelope = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus} returns this
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.clearEnvelope = function() {
  return this.setEnvelope(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.hasEnvelope = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Type type = 2;
 * @return {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.Type}
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.getType = function() {
  return /** @type {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.Type} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.Type} value
 * @return {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus} returns this
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional sensoris.protobuf.types.base.SystemStatus status = 3;
 * @return {!proto.sensoris.protobuf.types.base.SystemStatus}
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.getStatus = function() {
  return /** @type {!proto.sensoris.protobuf.types.base.SystemStatus} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.sensoris.protobuf.types.base.SystemStatus} value
 * @return {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus} returns this
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional sensoris.protobuf.types.base.Int64Value selected_speed = 4;
 * @return {?proto.sensoris.protobuf.types.base.Int64Value}
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.getSelectedSpeed = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.Int64Value} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.Int64Value, 4));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.Int64Value|undefined} value
 * @return {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus} returns this
*/
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.setSelectedSpeed = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus} returns this
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.clearSelectedSpeed = function() {
  return this.setSelectedSpeed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.hasSelectedSpeed = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional sensoris.protobuf.types.base.Int64Value selected_time_to_lead_vehicle = 5;
 * @return {?proto.sensoris.protobuf.types.base.Int64Value}
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.getSelectedTimeToLeadVehicle = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.Int64Value} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.Int64Value, 5));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.Int64Value|undefined} value
 * @return {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus} returns this
*/
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.setSelectedTimeToLeadVehicle = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus} returns this
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.clearSelectedTimeToLeadVehicle = function() {
  return this.setSelectedTimeToLeadVehicle(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.prototype.hasSelectedTimeToLeadVehicle = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.repeatedFields_ = [2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.powertrain.PowertrainCategory} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.toObject = function(includeInstance, msg) {
  var f, obj = {
    envelope: (f = msg.getEnvelope()) && sensoris_protobuf_types_base_pb.CategoryEnvelope.toObject(includeInstance, f),
    engineStatusList: jspb.Message.toObjectList(msg.getEngineStatusList(),
    proto.sensoris.protobuf.categories.powertrain.EngineStatus.toObject, includeInstance),
    transmissionStatusList: jspb.Message.toObjectList(msg.getTransmissionStatusList(),
    proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.toObject, includeInstance),
    cruiseControlStatusList: jspb.Message.toObjectList(msg.getCruiseControlStatusList(),
    proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.powertrain.PowertrainCategory}
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.powertrain.PowertrainCategory;
  return proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.powertrain.PowertrainCategory} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.powertrain.PowertrainCategory}
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new sensoris_protobuf_types_base_pb.CategoryEnvelope;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.CategoryEnvelope.deserializeBinaryFromReader);
      msg.setEnvelope(value);
      break;
    case 2:
      var value = new proto.sensoris.protobuf.categories.powertrain.EngineStatus;
      reader.readMessage(value,proto.sensoris.protobuf.categories.powertrain.EngineStatus.deserializeBinaryFromReader);
      msg.addEngineStatus(value);
      break;
    case 3:
      var value = new proto.sensoris.protobuf.categories.powertrain.TransmissionStatus;
      reader.readMessage(value,proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.deserializeBinaryFromReader);
      msg.addTransmissionStatus(value);
      break;
    case 4:
      var value = new proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus;
      reader.readMessage(value,proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.deserializeBinaryFromReader);
      msg.addCruiseControlStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.powertrain.PowertrainCategory} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvelope();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      sensoris_protobuf_types_base_pb.CategoryEnvelope.serializeBinaryToWriter
    );
  }
  f = message.getEngineStatusList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.sensoris.protobuf.categories.powertrain.EngineStatus.serializeBinaryToWriter
    );
  }
  f = message.getTransmissionStatusList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.sensoris.protobuf.categories.powertrain.TransmissionStatus.serializeBinaryToWriter
    );
  }
  f = message.getCruiseControlStatusList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus.serializeBinaryToWriter
    );
  }
};


/**
 * optional sensoris.protobuf.types.base.CategoryEnvelope envelope = 1;
 * @return {?proto.sensoris.protobuf.types.base.CategoryEnvelope}
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.getEnvelope = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.CategoryEnvelope} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.CategoryEnvelope, 1));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.CategoryEnvelope|undefined} value
 * @return {!proto.sensoris.protobuf.categories.powertrain.PowertrainCategory} returns this
*/
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.setEnvelope = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.powertrain.PowertrainCategory} returns this
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.clearEnvelope = function() {
  return this.setEnvelope(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.hasEnvelope = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated EngineStatus engine_status = 2;
 * @return {!Array<!proto.sensoris.protobuf.categories.powertrain.EngineStatus>}
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.getEngineStatusList = function() {
  return /** @type{!Array<!proto.sensoris.protobuf.categories.powertrain.EngineStatus>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sensoris.protobuf.categories.powertrain.EngineStatus, 2));
};


/**
 * @param {!Array<!proto.sensoris.protobuf.categories.powertrain.EngineStatus>} value
 * @return {!proto.sensoris.protobuf.categories.powertrain.PowertrainCategory} returns this
*/
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.setEngineStatusList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.sensoris.protobuf.categories.powertrain.EngineStatus=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sensoris.protobuf.categories.powertrain.EngineStatus}
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.addEngineStatus = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.sensoris.protobuf.categories.powertrain.EngineStatus, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sensoris.protobuf.categories.powertrain.PowertrainCategory} returns this
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.clearEngineStatusList = function() {
  return this.setEngineStatusList([]);
};


/**
 * repeated TransmissionStatus transmission_status = 3;
 * @return {!Array<!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus>}
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.getTransmissionStatusList = function() {
  return /** @type{!Array<!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sensoris.protobuf.categories.powertrain.TransmissionStatus, 3));
};


/**
 * @param {!Array<!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus>} value
 * @return {!proto.sensoris.protobuf.categories.powertrain.PowertrainCategory} returns this
*/
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.setTransmissionStatusList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sensoris.protobuf.categories.powertrain.TransmissionStatus}
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.addTransmissionStatus = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.sensoris.protobuf.categories.powertrain.TransmissionStatus, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sensoris.protobuf.categories.powertrain.PowertrainCategory} returns this
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.clearTransmissionStatusList = function() {
  return this.setTransmissionStatusList([]);
};


/**
 * repeated CruiseControlStatus cruise_control_status = 4;
 * @return {!Array<!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus>}
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.getCruiseControlStatusList = function() {
  return /** @type{!Array<!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus, 4));
};


/**
 * @param {!Array<!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus>} value
 * @return {!proto.sensoris.protobuf.categories.powertrain.PowertrainCategory} returns this
*/
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.setCruiseControlStatusList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus}
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.addCruiseControlStatus = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.sensoris.protobuf.categories.powertrain.CruiseControlStatus, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sensoris.protobuf.categories.powertrain.PowertrainCategory} returns this
 */
proto.sensoris.protobuf.categories.powertrain.PowertrainCategory.prototype.clearCruiseControlStatusList = function() {
  return this.setCruiseControlStatusList([]);
};


goog.object.extend(exports, proto.sensoris.protobuf.categories.powertrain);
