// source: sensoris/protobuf/categories/traffic_maneuver.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var sensoris_protobuf_types_base_pb = require('../../../sensoris/protobuf/types/base_pb.js');
goog.object.extend(proto, sensoris_protobuf_types_base_pb);
goog.exportSymbol('proto.sensoris.protobuf.categories.trafficmaneuver.Charging', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.trafficmaneuver.Charging.Type', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.Type', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.trafficmaneuver.Refueling', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.Type', null, global);
goog.exportSymbol('proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.displayName = 'proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.displayName = 'proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensoris.protobuf.categories.trafficmaneuver.Charging, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.trafficmaneuver.Charging.displayName = 'proto.sensoris.protobuf.categories.trafficmaneuver.Charging';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensoris.protobuf.categories.trafficmaneuver.Refueling, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.displayName = 'proto.sensoris.protobuf.categories.trafficmaneuver.Refueling';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.repeatedFields_, null);
};
goog.inherits(proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.displayName = 'proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.toObject = function(includeInstance, msg) {
  var f, obj = {
    envelope: (f = msg.getEnvelope()) && sensoris_protobuf_types_base_pb.EventEnvelope.toObject(includeInstance, f),
    typeAndConfidence: (f = msg.getTypeAndConfidence()) && proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver;
  return proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new sensoris_protobuf_types_base_pb.EventEnvelope;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.EventEnvelope.deserializeBinaryFromReader);
      msg.setEnvelope(value);
      break;
    case 2:
      var value = new proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence;
      reader.readMessage(value,proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.deserializeBinaryFromReader);
      msg.setTypeAndConfidence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvelope();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      sensoris_protobuf_types_base_pb.EventEnvelope.serializeBinaryToWriter
    );
  }
  f = message.getTypeAndConfidence();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    confidence: (f = msg.getConfidence()) && sensoris_protobuf_types_base_pb.Confidence.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence;
  return proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new sensoris_protobuf_types_base_pb.Confidence;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.Confidence.deserializeBinaryFromReader);
      msg.setConfidence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getConfidence();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      sensoris_protobuf_types_base_pb.Confidence.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.Type = {
  UNKNOWN_TYPE: 0,
  EVASIVE: 1,
  LANE_CHANGE: 2,
  LANE_CHANGE_RIGHT: 3,
  LANE_CHANGE_LEFT: 4,
  OVERTAKING: 5,
  INTERSECTION_STOP: 6,
  TURNING: 7,
  TURNING_RIGHT: 8,
  TURNING_LEFT: 9,
  SHARP_TURNING_RIGHT: 10,
  SHARP_TURNING_LEFT: 11,
  ACCELERATING: 12,
  BREAKING: 13
};

/**
 * optional Type type = 1;
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.Type}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.prototype.getType = function() {
  return /** @type {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.Type} value
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence} returns this
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional sensoris.protobuf.types.base.Confidence confidence = 2;
 * @return {?proto.sensoris.protobuf.types.base.Confidence}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.prototype.getConfidence = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.Confidence} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.Confidence, 2));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.Confidence|undefined} value
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence} returns this
*/
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.prototype.setConfidence = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence} returns this
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.prototype.clearConfidence = function() {
  return this.setConfidence(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence.prototype.hasConfidence = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional sensoris.protobuf.types.base.EventEnvelope envelope = 1;
 * @return {?proto.sensoris.protobuf.types.base.EventEnvelope}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.prototype.getEnvelope = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.EventEnvelope} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.EventEnvelope, 1));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.EventEnvelope|undefined} value
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver} returns this
*/
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.prototype.setEnvelope = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver} returns this
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.prototype.clearEnvelope = function() {
  return this.setEnvelope(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.prototype.hasEnvelope = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TypeAndConfidence type_and_confidence = 2;
 * @return {?proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.prototype.getTypeAndConfidence = function() {
  return /** @type{?proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence} */ (
    jspb.Message.getWrapperField(this, proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence, 2));
};


/**
 * @param {?proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.TypeAndConfidence|undefined} value
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver} returns this
*/
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.prototype.setTypeAndConfidence = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver} returns this
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.prototype.clearTypeAndConfidence = function() {
  return this.setTypeAndConfidence(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.prototype.hasTypeAndConfidence = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.trafficmaneuver.Charging.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.toObject = function(includeInstance, msg) {
  var f, obj = {
    envelope: (f = msg.getEnvelope()) && sensoris_protobuf_types_base_pb.EventEnvelope.toObject(includeInstance, f),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0),
    voltageAndAccuracy: (f = msg.getVoltageAndAccuracy()) && sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy.toObject(includeInstance, f),
    currentAndAccuracy: (f = msg.getCurrentAndAccuracy()) && sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.trafficmaneuver.Charging;
  return proto.sensoris.protobuf.categories.trafficmaneuver.Charging.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new sensoris_protobuf_types_base_pb.EventEnvelope;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.EventEnvelope.deserializeBinaryFromReader);
      msg.setEnvelope(value);
      break;
    case 2:
      var value = /** @type {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 3:
      var value = new sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy.deserializeBinaryFromReader);
      msg.setVoltageAndAccuracy(value);
      break;
    case 4:
      var value = new sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy.deserializeBinaryFromReader);
      msg.setCurrentAndAccuracy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.trafficmaneuver.Charging.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvelope();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      sensoris_protobuf_types_base_pb.EventEnvelope.serializeBinaryToWriter
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getVoltageAndAccuracy();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy.serializeBinaryToWriter
    );
  }
  f = message.getCurrentAndAccuracy();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.Type = {
  UNKNOWN_TYPE: 0,
  PORT_J1772: 1,
  CHADEMO: 2,
  SAE_COMBO: 3,
  TESLA_HPWC: 4,
  TESLA_SUPERCHARGER: 5
};

/**
 * optional sensoris.protobuf.types.base.EventEnvelope envelope = 1;
 * @return {?proto.sensoris.protobuf.types.base.EventEnvelope}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.prototype.getEnvelope = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.EventEnvelope} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.EventEnvelope, 1));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.EventEnvelope|undefined} value
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging} returns this
*/
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.prototype.setEnvelope = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging} returns this
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.prototype.clearEnvelope = function() {
  return this.setEnvelope(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.prototype.hasEnvelope = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Type type = 2;
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging.Type}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.prototype.getType = function() {
  return /** @type {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging.Type} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging.Type} value
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging} returns this
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional sensoris.protobuf.types.base.Int64ValueAndAccuracy voltage_and_accuracy = 3;
 * @return {?proto.sensoris.protobuf.types.base.Int64ValueAndAccuracy}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.prototype.getVoltageAndAccuracy = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.Int64ValueAndAccuracy} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy, 3));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.Int64ValueAndAccuracy|undefined} value
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging} returns this
*/
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.prototype.setVoltageAndAccuracy = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging} returns this
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.prototype.clearVoltageAndAccuracy = function() {
  return this.setVoltageAndAccuracy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.prototype.hasVoltageAndAccuracy = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional sensoris.protobuf.types.base.Int64ValueAndAccuracy current_and_accuracy = 4;
 * @return {?proto.sensoris.protobuf.types.base.Int64ValueAndAccuracy}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.prototype.getCurrentAndAccuracy = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.Int64ValueAndAccuracy} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy, 4));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.Int64ValueAndAccuracy|undefined} value
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging} returns this
*/
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.prototype.setCurrentAndAccuracy = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging} returns this
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.prototype.clearCurrentAndAccuracy = function() {
  return this.setCurrentAndAccuracy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Charging.prototype.hasCurrentAndAccuracy = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.toObject = function(includeInstance, msg) {
  var f, obj = {
    envelope: (f = msg.getEnvelope()) && sensoris_protobuf_types_base_pb.EventEnvelope.toObject(includeInstance, f),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0),
    quantityToFullAndAccuracy: (f = msg.getQuantityToFullAndAccuracy()) && sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.trafficmaneuver.Refueling;
  return proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new sensoris_protobuf_types_base_pb.EventEnvelope;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.EventEnvelope.deserializeBinaryFromReader);
      msg.setEnvelope(value);
      break;
    case 2:
      var value = /** @type {!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 3:
      var value = new sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy.deserializeBinaryFromReader);
      msg.setQuantityToFullAndAccuracy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvelope();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      sensoris_protobuf_types_base_pb.EventEnvelope.serializeBinaryToWriter
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getQuantityToFullAndAccuracy();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.Type = {
  UNKNOWN_TYPE: 0,
  PETROL_PREMIUM: 1,
  PETROL_SUPER: 2,
  DIESEL: 3,
  LPG: 4,
  CNG: 5,
  BIO_DIESEL: 6,
  BIO_ETHANOL: 7,
  HYDROGEN: 8
};

/**
 * optional sensoris.protobuf.types.base.EventEnvelope envelope = 1;
 * @return {?proto.sensoris.protobuf.types.base.EventEnvelope}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.prototype.getEnvelope = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.EventEnvelope} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.EventEnvelope, 1));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.EventEnvelope|undefined} value
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling} returns this
*/
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.prototype.setEnvelope = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling} returns this
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.prototype.clearEnvelope = function() {
  return this.setEnvelope(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.prototype.hasEnvelope = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Type type = 2;
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.Type}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.prototype.getType = function() {
  return /** @type {!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.Type} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.Type} value
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling} returns this
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional sensoris.protobuf.types.base.Int64ValueAndAccuracy quantity_to_full_and_accuracy = 3;
 * @return {?proto.sensoris.protobuf.types.base.Int64ValueAndAccuracy}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.prototype.getQuantityToFullAndAccuracy = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.Int64ValueAndAccuracy} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.Int64ValueAndAccuracy, 3));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.Int64ValueAndAccuracy|undefined} value
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling} returns this
*/
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.prototype.setQuantityToFullAndAccuracy = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling} returns this
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.prototype.clearQuantityToFullAndAccuracy = function() {
  return this.setQuantityToFullAndAccuracy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.prototype.hasQuantityToFullAndAccuracy = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.repeatedFields_ = [2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.toObject = function(opt_includeInstance) {
  return proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.toObject = function(includeInstance, msg) {
  var f, obj = {
    envelope: (f = msg.getEnvelope()) && sensoris_protobuf_types_base_pb.CategoryEnvelope.toObject(includeInstance, f),
    maneuverList: jspb.Message.toObjectList(msg.getManeuverList(),
    proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.toObject, includeInstance),
    chargingList: jspb.Message.toObjectList(msg.getChargingList(),
    proto.sensoris.protobuf.categories.trafficmaneuver.Charging.toObject, includeInstance),
    refuelingList: jspb.Message.toObjectList(msg.getRefuelingList(),
    proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory;
  return proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new sensoris_protobuf_types_base_pb.CategoryEnvelope;
      reader.readMessage(value,sensoris_protobuf_types_base_pb.CategoryEnvelope.deserializeBinaryFromReader);
      msg.setEnvelope(value);
      break;
    case 2:
      var value = new proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver;
      reader.readMessage(value,proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.deserializeBinaryFromReader);
      msg.addManeuver(value);
      break;
    case 3:
      var value = new proto.sensoris.protobuf.categories.trafficmaneuver.Charging;
      reader.readMessage(value,proto.sensoris.protobuf.categories.trafficmaneuver.Charging.deserializeBinaryFromReader);
      msg.addCharging(value);
      break;
    case 4:
      var value = new proto.sensoris.protobuf.categories.trafficmaneuver.Refueling;
      reader.readMessage(value,proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.deserializeBinaryFromReader);
      msg.addRefueling(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvelope();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      sensoris_protobuf_types_base_pb.CategoryEnvelope.serializeBinaryToWriter
    );
  }
  f = message.getManeuverList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver.serializeBinaryToWriter
    );
  }
  f = message.getChargingList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.sensoris.protobuf.categories.trafficmaneuver.Charging.serializeBinaryToWriter
    );
  }
  f = message.getRefuelingList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.sensoris.protobuf.categories.trafficmaneuver.Refueling.serializeBinaryToWriter
    );
  }
};


/**
 * optional sensoris.protobuf.types.base.CategoryEnvelope envelope = 1;
 * @return {?proto.sensoris.protobuf.types.base.CategoryEnvelope}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.getEnvelope = function() {
  return /** @type{?proto.sensoris.protobuf.types.base.CategoryEnvelope} */ (
    jspb.Message.getWrapperField(this, sensoris_protobuf_types_base_pb.CategoryEnvelope, 1));
};


/**
 * @param {?proto.sensoris.protobuf.types.base.CategoryEnvelope|undefined} value
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory} returns this
*/
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.setEnvelope = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory} returns this
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.clearEnvelope = function() {
  return this.setEnvelope(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.hasEnvelope = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Maneuver maneuver = 2;
 * @return {!Array<!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver>}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.getManeuverList = function() {
  return /** @type{!Array<!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver, 2));
};


/**
 * @param {!Array<!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver>} value
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory} returns this
*/
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.setManeuverList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.addManeuver = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.sensoris.protobuf.categories.trafficmaneuver.Maneuver, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory} returns this
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.clearManeuverList = function() {
  return this.setManeuverList([]);
};


/**
 * repeated Charging charging = 3;
 * @return {!Array<!proto.sensoris.protobuf.categories.trafficmaneuver.Charging>}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.getChargingList = function() {
  return /** @type{!Array<!proto.sensoris.protobuf.categories.trafficmaneuver.Charging>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sensoris.protobuf.categories.trafficmaneuver.Charging, 3));
};


/**
 * @param {!Array<!proto.sensoris.protobuf.categories.trafficmaneuver.Charging>} value
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory} returns this
*/
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.setChargingList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Charging}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.addCharging = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.sensoris.protobuf.categories.trafficmaneuver.Charging, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory} returns this
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.clearChargingList = function() {
  return this.setChargingList([]);
};


/**
 * repeated Refueling refueling = 4;
 * @return {!Array<!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling>}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.getRefuelingList = function() {
  return /** @type{!Array<!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sensoris.protobuf.categories.trafficmaneuver.Refueling, 4));
};


/**
 * @param {!Array<!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling>} value
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory} returns this
*/
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.setRefuelingList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.Refueling}
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.addRefueling = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.sensoris.protobuf.categories.trafficmaneuver.Refueling, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory} returns this
 */
proto.sensoris.protobuf.categories.trafficmaneuver.TrafficManeuverCategory.prototype.clearRefuelingList = function() {
  return this.setRefuelingList([]);
};


goog.object.extend(exports, proto.sensoris.protobuf.categories.trafficmaneuver);
