version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.0
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - 9200
      - 9300
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
